# Rename this file to languages.toml to enable multilingual support
[en]
    languageName      = "English"
    languagedirection = "ltr"
    title             = "Blog page"
    weight            = 1

[jp]
    languageName      = "Japanese"
    languagedirection = "ltr"
    title             = ""
    weight            = 1
